### ISSUE TITLE
Please dual license

### ISSUE THREAD

**Issue by MithicSpirit** [omega-mc/soaring-clouds#4]
The CC0 license retains patent rights, which leads some groups (like [the OSI](https://opensource.org/faq#cc-zero)) to not consider it an open source license. [Here](https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses#cite_ref-60) is a comparison of open source licenses on Wikipedia; I would recommend MIT, but it's entirely up to you.

Also, I would recommend adding actual LICENSE files rather than just leaving it at the end of the README.

**Comment by Draylar** [comment]
Switched to MIT, thank you for letting me know!

**Comment by MithicSpirit** [comment]
Thanks! 

Also note that MIT does not release it into the public domain, while CC0 does. This means that people have to credit you if they use your code. If you do not wish to require that, then you can have two licenses (usually I've seen this as having two files, `LICENSE-MIT` and `LICENSE-CC0`), and anyone who uses it can choose which terms they want to follow.
